# Generated by Django 5.1.8 on 2025-04-16 07:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teams', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(choices=[('PG', 'Point Guard'), ('SG', 'Shooting Guard'), ('SF', 'Small Forward'), ('PF', 'Power Forward'), ('C', 'Center')], db_index=True, help_text='Primary playing position', max_length=2)),
                ('secondary_position', models.CharField(blank=True, choices=[('PG', 'Point Guard'), ('SG', 'Shooting Guard'), ('SF', 'Small Forward'), ('PF', 'Power Forward'), ('C', 'Center')], help_text='Secondary playing position, if any', max_length=2, null=True)),
                ('jersey_number', models.PositiveSmallIntegerField(help_text="Player's jersey number")),
                ('height_cm', models.PositiveSmallIntegerField(help_text='Height in centimeters')),
                ('weight_kg', models.PositiveSmallIntegerField(help_text='Weight in kilograms')),
                ('wingspan_cm', models.PositiveSmallIntegerField(blank=True, help_text='Wingspan in centimeters, if known', null=True)),
                ('date_of_birth', models.DateField(help_text="Player's date of birth")),
                ('nationality', models.CharField(db_index=True, help_text="Player's nationality", max_length=100)),
                ('birthplace', models.CharField(help_text="Player's place of birth", max_length=200)),
                ('draft_year', models.PositiveSmallIntegerField(blank=True, help_text='Year the player was drafted, if applicable', null=True)),
                ('draft_position', models.PositiveSmallIntegerField(blank=True, help_text="Player's draft position, if applicable", null=True)),
                ('profile_image', models.ImageField(blank=True, help_text="Player's profile image", null=True, upload_to='player_profiles/')),
                ('biography', models.TextField(blank=True, help_text="Player's biography or career summary")),
                ('twitter_handle', models.CharField(blank=True, help_text="Player's Twitter handle", max_length=50)),
                ('instagram_handle', models.CharField(blank=True, help_text="Player's Instagram handle", max_length=50)),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Whether the player is currently active')),
                ('is_injured', models.BooleanField(default=False, help_text='Whether the player is currently injured')),
                ('injury_details', models.CharField(blank=True, help_text="Details about player's injury, if any", max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('team', models.ForeignKey(blank=True, help_text='Current team of the player', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='players', to='teams.team')),
                ('user', models.OneToOneField(help_text='User account linked to this player', on_delete=django.db.models.deletion.CASCADE, related_name='player_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Player',
                'verbose_name_plural': 'Players',
                'ordering': ['team', 'user__last_name', 'user__first_name'],
            },
        ),
        migrations.CreateModel(
            name='PlayerTeamHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(help_text='When the player joined this team')),
                ('end_date', models.DateTimeField(blank=True, help_text='When the player left this team', null=True)),
                ('transfer_notes', models.TextField(blank=True, help_text='Notes about the transfer (e.g., trade details, free agency)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('player', models.ForeignKey(help_text='Player whose team history is being tracked', on_delete=django.db.models.deletion.CASCADE, to='players.player')),
                ('team', models.ForeignKey(help_text='Team the player belonged to', on_delete=django.db.models.deletion.CASCADE, to='teams.team')),
            ],
            options={
                'verbose_name': 'Player Team History',
                'verbose_name_plural': 'Player Team Histories',
                'ordering': ['-start_date'],
            },
        ),
        migrations.AddIndex(
            model_name='player',
            index=models.Index(fields=['user'], name='players_pla_user_id_975093_idx'),
        ),
        migrations.AddIndex(
            model_name='player',
            index=models.Index(fields=['team', 'is_active'], name='players_pla_team_id_1a80c1_idx'),
        ),
        migrations.AddIndex(
            model_name='player',
            index=models.Index(fields=['position', 'is_active'], name='players_pla_positio_efd98c_idx'),
        ),
        migrations.AddIndex(
            model_name='player',
            index=models.Index(fields=['nationality'], name='players_pla_nationa_103a64_idx'),
        ),
        migrations.AddIndex(
            model_name='playerteamhistory',
            index=models.Index(fields=['player', '-start_date'], name='players_pla_player__6ff0ab_idx'),
        ),
        migrations.AddIndex(
            model_name='playerteamhistory',
            index=models.Index(fields=['team', '-start_date'], name='players_pla_team_id_049421_idx'),
        ),
    ]
