# Generated by Django 5.1.8 on 2025-04-16 07:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='League',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, help_text='Name of the league', max_length=100, unique=True)),
                ('country', models.CharField(db_index=True, help_text='Country where the league operates', max_length=100)),
                ('logo', models.ImageField(blank=True, help_text='Logo image for the league', null=True, upload_to='league_logos/')),
                ('description', models.TextField(blank=True, help_text='Description of the league')),
                ('season_start', models.DateField(blank=True, help_text='Start date of the current season', null=True)),
                ('season_end', models.DateField(blank=True, help_text='End date of the current season', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'League',
                'verbose_name_plural': 'Leagues',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['country', 'name'], name='teams_leagu_country_722ea1_idx')],
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, help_text='Name of the team', max_length=100)),
                ('logo', models.ImageField(blank=True, help_text='Logo image for the team', null=True, upload_to='team_logos/')),
                ('founded_year', models.IntegerField(blank=True, help_text='Year the team was founded', null=True)),
                ('home_venue', models.CharField(help_text='Home venue where the team plays', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Description or history of the team')),
                ('website', models.URLField(blank=True, help_text='Official team website')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Whether the team is currently active')),
                ('team_colors', models.CharField(blank=True, help_text="Team colors (e.g., 'Red, White, Blue')", max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('league', models.ForeignKey(help_text='League this team belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='teams.league')),
            ],
            options={
                'verbose_name': 'Team',
                'verbose_name_plural': 'Teams',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['league', 'name'], name='teams_team_league__ab1470_idx'), models.Index(fields=['is_active'], name='teams_team_is_acti_6dafc6_idx')],
                'unique_together': {('name', 'league')},
            },
        ),
    ]
